RegExpInterpreter
alexander-kurdakov/RegExpInterpreter pull request #1
Opened 2021-10-28 10:02 UTC by alexander-kurdakov

2021-11-03 08:00 UTC, gsvgit requested changes

2021-11-03 08:00 UTC, gsvgit commented on src/Interpreter/Parser.fsy
> +eof: EOF {1}
А зачем тут 1? Почему именно она?

2021-11-03 08:00 UTC, gsvgit commented on tests/Interpreter.Tests/Tests.fs
> +            Expect.equal "True" (evaluateExpr (textToAST x)).ToString ""
А что сообщения везде пустые?

2021-11-03 08:00 UTC, gsvgit commented on tests/Interpreter.Tests/Tests.fs
> +        testCase "fail test #2" <| fun _ ->
А какие-нибудь более сложные композиции не хотите потестировать? С пересечением, например.

2021-11-03 09:51 UTC, alexander-kurdakov commented on src/Interpreter/Parser.fsy
> +eof: EOF {1}
В Вашем парсере так же, а в документации ничего не написано про это.

2021-11-03 10:03 UTC, alexander-kurdakov commented on src/Interpreter/Parser.fsy
> +eof: EOF {1}
В примере из документации обошлись без него.

2021-11-03 11:12 UTC, alexander-kurdakov commented on tests/Interpreter.Tests/Tests.fs
> +            Expect.equal "True" (evaluateExpr (textToAST x)).ToString ""
Исправил.

2021-11-03 11:12 UTC, alexander-kurdakov commented on tests/Interpreter.Tests/Tests.fs
> +        testCase "fail test #2" <| fun _ ->
Добавил.

2021-11-08 08:54 UTC, gsvgit approved these changes
Пусть будет.

2021-11-08 08:54 UTC, gsvgit commented on src/Interpreter/Parser.fsy
> +eof: EOF {1}
Кажется, надо разобраться с тем, что здесь происходит.

2021-11-08 13:57 UTC, merged